
test2 :
	PATH=/home/mdupont/gocode/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:~/gocode/bin/	GOPATH=/home/mdupont/gocode/ ./go-to-protobuf   --only-idl  --packages github.com/h4ck3rm1k3/gogccintro/fakego/ast

build :
	PATH=/home/mdupont/gocode/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:~/gocode/bin/	GOPATH=/home/mdupont/gocode/  go build 
